name: Update version.json with Commit Message

on:
  push:
    branches:
      - main

jobs:
  update-version-with-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # To get the current and previous commit

      - name: Extract version from build.gradle.kts
        id: extract_version
        run: |
          VERSION_NAME=$(grep -oP 'versionName\s*=\s*"\K[0-9.]+' app/build.gradle.kts)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Get latest commit message
        id: commit_message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:%s)
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV
          echo "Commit message: $COMMIT_MSG"

      - name: Update version.json
        run: |
          echo "{
            \"version\": \"v${{ env.VERSION_NAME }}\",
            \"url\": \"https://github.com/${{ github.repository }}/releases/tag/v${{ env.VERSION_NAME }}\",
            \"commit_message\": \"${{ env.COMMIT_MSG }}\"
          }" > version.json

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version.json
          git commit -m "Update version.json with latest commit message"
          git push origin main 