name: Update version.json

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main # Ensure the master branch is checked out
          fetch-depth: 2 # To get the commit message

      - name: Get commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:%s)
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV
          echo "Commit message: $COMMIT_MSG"

      - name: Update version.json
        run: |
          echo "{
            \"version\": \"${{ github.event.release.tag_name }}\",
            \"url\": \"${{ github.event.release.html_url }}\",
            \"message\": \"${{ env.COMMIT_MSG }}\"
          }" > version.json

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version.json
          git commit -m "Update version.json to ${{ github.event.release.tag_name }}"
          git push origin main